### PR TITLE
Fix "items" attribute in array schemas

### LINKED ISSUE #156: Certificate's `matches` should use `items`
Since the `matches` field is an array i believe it should declare its child  as `items` instead of `item`. 
See below:

https://github.com/postmanlabs/schemas/blob/e6429ead7a805985e68f9e1fe49ec5a4c5234d5a/schemas/draft-07/v2.1.0/collection/certificate.json#L11-L14

### PR DESCRIPTION
**Pull request by jmini**
Fixes #156 

Inside a schema with type `"array"`, the attribute is called `"items"` and not `"item"`.

---

I hope this is the right place to propose the change. The wrong value can also be seen here:
http://schema.getpostman.com/collection/json/v2.1.0/draft-04/collection.json

### CODE REVIEW

**Review by codenirvana — CHANGES_REQUESTED** [review]
LGTM 👍 

Can we add scaled-down [examples](https://github.com/postmanlabs/schemas/tree/develop/examples) for `v2.0.0` and `v2.1.0` collections having `certificate` property in request?

These examples are used as fixtures in tests.

**Comment by jmini** [comment]
I never used Certificates with Postman. I found this documentation https://learning.postman.com/docs/sending-requests/certificates/ but it seems to be for Global Certificates, not the one in the collection in the `"certificate"` attribute of a request, as defined in this schema:

https://github.com/postmanlabs/schemas/blob/e6429ead7a805985e68f9e1fe49ec5a4c5234d5a/schemas/draft-04/v2.1.0/collection/request.json#L7-L29

So I am a little bit lost about how to create a collection having the attribute set.

**Comment by jmini** [comment]
@codenirvana: can you help me with the examples you requested ? Otherwise I fear I will not be able to finish this PR.

**Comment by codenirvana** [comment]
Updated examples in https://github.com/postmanlabs/schemas/commit/2d4a94fa4df0688e5e21bcc99cbc360a27ab0b4c

**Review by codenirvana — APPROVED** [review]

**Pull request merged**
